// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type DeliveryAttempt struct {
	ID            int64
	EventID       int64
	AttemptNumber int32
	State         string
	StatusCode    pgtype.Int4
	ErrorType     pgtype.Text
	ErrorMessage  pgtype.Text
	StartedAt     pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type Event struct {
	ID              int64
	SourceID        int64
	DedupHash       pgtype.Text
	Method          string
	IngressPath     string
	RemoteAddress   *netip.Addr
	QueryParams     []byte
	RawHeaders      []byte
	Body            []byte
	BodyContentType string
	ReceivedAt      pgtype.Timestamptz
}

type Source struct {
	ID            int64
	PublicID      pgtype.UUID
	EgressUrl     string
	StaticHeaders []byte
	Status        string
	StatusReason  pgtype.Text
	Description   pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DisableAt     pgtype.Timestamptz
}
