// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Endpoint struct {
	ID             int64
	UserID         pgtype.Int8
	PublicKey      string
	Name           string
	Description    pgtype.Text
	CreatedAt      pgtype.Timestamp
	LastReceivedAt pgtype.Timestamp
}

type Event struct {
	ID          int64
	EndpointID  pgtype.Int8
	ReceivedAt  pgtype.Timestamp
	Headers     []byte
	Body        []byte
	Size        int32
	SourceIp    netip.Addr
	ContentType string
	EventHash   pgtype.Text
}

type User struct {
	ID        int64
	Email     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
