// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeliveryAttempt = `-- name: CreateDeliveryAttempt :one
INSERT INTO delivery_attempts (
    event_id,
    attempt_number,
    state,
    status_code,
    error_type,
    error_message,
    started_at,
    finished_at,
    next_attempt_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id
`

type CreateDeliveryAttemptParams struct {
	EventID       int64
	AttemptNumber int32
	State         string
	StatusCode    pgtype.Int4
	ErrorType     pgtype.Text
	ErrorMessage  pgtype.Text
	StartedAt     pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
	NextAttemptAt pgtype.Timestamptz
}

func (q *Queries) CreateDeliveryAttempt(ctx context.Context, arg CreateDeliveryAttemptParams) (int64, error) {
	row := q.db.QueryRow(ctx, createDeliveryAttempt,
		arg.EventID,
		arg.AttemptNumber,
		arg.State,
		arg.StatusCode,
		arg.ErrorType,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.FinishedAt,
		arg.NextAttemptAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    source_id,
    dedup_hash,
    method,
    ingress_path,
    remote_address,
    query_params,
    raw_headers,
    body,
    body_content_type
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id
`

type CreateEventParams struct {
	SourceID        int64
	DedupHash       pgtype.Text
	Method          string
	IngressPath     string
	RemoteAddress   *netip.Addr
	QueryParams     []byte
	RawHeaders      []byte
	Body            []byte
	BodyContentType string
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.SourceID,
		arg.DedupHash,
		arg.Method,
		arg.IngressPath,
		arg.RemoteAddress,
		arg.QueryParams,
		arg.RawHeaders,
		arg.Body,
		arg.BodyContentType,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSource = `-- name: CreateSource :one
INSERT INTO sources (
    egress_url,
    static_headers,
    description
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, public_id, egress_url, static_headers, status, status_reason, description, created_at, updated_at, disable_at
`

type CreateSourceParams struct {
	EgressUrl     string
	StaticHeaders []byte
	Description   pgtype.Text
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource, arg.EgressUrl, arg.StaticHeaders, arg.Description)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.EgressUrl,
		&i.StaticHeaders,
		&i.Status,
		&i.StatusReason,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisableAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT
    id,
    source_id,
    dedup_hash,
    method,
    ingress_path,
    remote_address,
    query_params,
    raw_headers,
    body,
    body_content_type,
    received_at
FROM
    events
WHERE
    id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DedupHash,
		&i.Method,
		&i.IngressPath,
		&i.RemoteAddress,
		&i.QueryParams,
		&i.RawHeaders,
		&i.Body,
		&i.BodyContentType,
		&i.ReceivedAt,
	)
	return i, err
}

const getSourceByID = `-- name: GetSourceByID :one
SELECT
    id,
    public_id,
    egress_url,
    static_headers,
    status,
    status_reason,
    description,
    created_at,
    updated_at,
    disable_at
FROM
    sources
WHERE
    id = $1
`

func (q *Queries) GetSourceByID(ctx context.Context, id int64) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByID, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.EgressUrl,
		&i.StaticHeaders,
		&i.Status,
		&i.StatusReason,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisableAt,
	)
	return i, err
}

const getSourceByPublicID = `-- name: GetSourceByPublicID :one
SELECT
    id,
    public_id,
    egress_url,
    static_headers,
    status,
    status_reason,
    description,
    created_at,
    updated_at,
    disable_at
FROM
    sources
WHERE
    public_id = $1
`

func (q *Queries) GetSourceByPublicID(ctx context.Context, publicID pgtype.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByPublicID, publicID)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.EgressUrl,
		&i.StaticHeaders,
		&i.Status,
		&i.StatusReason,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisableAt,
	)
	return i, err
}

const listDeliveryAttemptsByEvent = `-- name: ListDeliveryAttemptsByEvent :many
SELECT
    id,
    event_id,
    attempt_number,
    state,
    status_code,
    error_type,
    error_message,
    started_at,
    finished_at,
    created_at,
    next_attempt_at
FROM
    delivery_attempts
WHERE
    event_id = $1
ORDER BY
    created_at DESC
`

func (q *Queries) ListDeliveryAttemptsByEvent(ctx context.Context, eventID int64) ([]DeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, listDeliveryAttemptsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryAttempt
	for rows.Next() {
		var i DeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.AttemptNumber,
			&i.State,
			&i.StatusCode,
			&i.ErrorType,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsBySource = `-- name: ListEventsBySource :many
SELECT
    id,
    source_id,
    dedup_hash,
    method,
    ingress_path,
    remote_address,
    query_params,
    raw_headers,
    body,
    body_content_type,
    received_at
FROM
    events
WHERE
    source_id = $1
ORDER BY
    received_at DESC
`

func (q *Queries) ListEventsBySource(ctx context.Context, sourceID int64) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.DedupHash,
			&i.Method,
			&i.IngressPath,
			&i.RemoteAddress,
			&i.QueryParams,
			&i.RawHeaders,
			&i.Body,
			&i.BodyContentType,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDeliveryAttempts = `-- name: ListPendingDeliveryAttempts :many
UPDATE delivery_attempts
SET
    state = 'in_flight'
FROM
    events
INNER JOIN sources
        ON events.source_id = sources.id
WHERE
    delivery_attempts.event_id = events.id
    AND delivery_attempts.state = 'pending'
    AND sources.status = 'active'
RETURNING
    delivery_attempts.id,
    delivery_attempts.event_id,
    delivery_attempts.attempt_number
`

type ListPendingDeliveryAttemptsRow struct {
	ID            int64
	EventID       int64
	AttemptNumber int32
}

func (q *Queries) ListPendingDeliveryAttempts(ctx context.Context) ([]ListPendingDeliveryAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listPendingDeliveryAttempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingDeliveryAttemptsRow
	for rows.Next() {
		var i ListPendingDeliveryAttemptsRow
		if err := rows.Scan(&i.ID, &i.EventID, &i.AttemptNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT
    id,
    public_id,
    egress_url,
    static_headers,
    status,
    status_reason,
    description,
    created_at,
    updated_at,
    disable_at
FROM
    sources
ORDER BY
    created_at DESC
`

func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.EgressUrl,
			&i.StaticHeaders,
			&i.Status,
			&i.StatusReason,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisableAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverStuckDeliveryAttempts = `-- name: RecoverStuckDeliveryAttempts :exec
UPDATE delivery_attempts
SET
    state = 'pending',
    started_at = NULL,
    finished_at = NULL
WHERE
    state = 'in_flight'
    AND started_at < NOW() - INTERVAL '15 minutes'
`

func (q *Queries) RecoverStuckDeliveryAttempts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, recoverStuckDeliveryAttempts)
	return err
}

const updateDeliveryAttempt = `-- name: UpdateDeliveryAttempt :exec
UPDATE delivery_attempts
SET
    state = $1,
    status_code = $2,
    error_type = $3,
    error_message = $4,
    started_at = CASE
        WHEN $1 = 'pending' THEN NULL
        ELSE COALESCE(started_at, $5)
    END,
    finished_at = CASE
        WHEN $1 IN ('pending', 'in_flight') THEN NULL
        ELSE COALESCE(finished_at, $6)
    END
WHERE
    id = $7
    AND state IN ('pending', 'in_flight')
`

type UpdateDeliveryAttemptParams struct {
	State        string
	StatusCode   pgtype.Int4
	ErrorType    pgtype.Text
	ErrorMessage pgtype.Text
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	ID           int64
}

func (q *Queries) UpdateDeliveryAttempt(ctx context.Context, arg UpdateDeliveryAttemptParams) error {
	_, err := q.db.Exec(ctx, updateDeliveryAttempt,
		arg.State,
		arg.StatusCode,
		arg.ErrorType,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}
