// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const listDeliveryAttemptsByEvent = `-- name: ListDeliveryAttemptsByEvent :many
SELECT
    id,
    event_id,
    attempt_number,
    state,
    status_code,
    error_type,
    error_message,
    started_at,
    finished_at,
    created_at
FROM
    delivery_attempts
WHERE
    event_id = $1
ORDER BY
    created_at DESC
`

func (q *Queries) ListDeliveryAttemptsByEvent(ctx context.Context, eventID int64) ([]DeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, listDeliveryAttemptsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryAttempt
	for rows.Next() {
		var i DeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.AttemptNumber,
			&i.State,
			&i.StatusCode,
			&i.ErrorType,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsBySource = `-- name: ListEventsBySource :many
SELECT
    id,
    source_id,
    dedup_hash,
    method,
    query_params,
    raw_headers,
    body,
    body_content_type,
    received_at
FROM
    events
WHERE
    source_id = $1
ORDER BY
    received_at DESC
`

func (q *Queries) ListEventsBySource(ctx context.Context, sourceID int64) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.DedupHash,
			&i.Method,
			&i.QueryParams,
			&i.RawHeaders,
			&i.Body,
			&i.BodyContentType,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT
    id,
    ingress_url,
    egress_url,
    static_headers,
    status,
    status_reason,
    description,
    created_at,
    updated_at,
    disable_at
FROM
    sources
ORDER BY
    created_at DESC
`

func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.IngressUrl,
			&i.EgressUrl,
			&i.StaticHeaders,
			&i.Status,
			&i.StatusReason,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisableAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
